apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yaml

commonLabels:
  app: miniqueue

images:
- name: miniqueue
  newName: docker.io/tomarrell/miniqueue
  newTag: v0.7.0

secretGenerator:
- name: tls
  files:
    - secrets/localhost.key
    - secrets/localhost.crt
