apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: miniqueue-statefulset
spec:
  serviceName: miniqueue
  replicas: 1
  template:
    spec:
      containers:
      - name: miniqueue
        image: miniqueue
        args:
          - "-db=/var/lib/miniqueue"
          - "-key=/tls/localhost.key"
          - "-cert=/tls/localhost.crt"
          - "-level=debug"
          - "-period=10s"
          - "-port=8080"
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: miniqueue-storage
            mountPath: /var/lib/miniqueue
          - name: tls-secrets
            mountPath: /tls
      volumes:
      - name: tls-secrets
        secret:
          secretName: tls
  volumeClaimTemplates:
  - metadata:
      name: miniqueue-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 1Gi
