apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: blog
        image: blog
        env:
        - name: RUST_LOG
          value: "blog=trace,actix_web=trace"
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: regcred
