kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: blog-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    # traefik.ingress.kubernetes.io/router.tls: "true"
    # traefik.ingress.kubernetes.io/router.tls.certresolver: default
spec:
  rules:
    - host: "blog.tomarrell.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: blog-service
                port:
                  number: 80
