apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

commonLabels:
  app: blog

images:
- name: blog
  newName: docker.io/tomarrell/personal
  newTag: blog-c0eb3dc
