apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- okapi-deployment.yaml

commonLabels:
  app: okapi

images:
- name: okapi
  newName: docker.io/tomarrell/personal
  newTag: latest

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: okapi-configmap
  files:
  - ./secrets/config.yaml

secretGenerator:
- name: regcred
  env: ./secrets/docker-auth.env
  type: kubernetes.io/dockerconfigjson
