apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

commonLabels:
  app: okapi

images:
- name: okapi
  newName: docker.io/tomarrell/personal
  newTag: latest

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: okapi-configmap
  files:
  - config.secret.yaml

secretGenerator:
- name: regcred
  env: docker-secret.env
  type: kubernetes.io/dockerconfigjson
