apiVersion: apps/v1
kind: Deployment
metadata:
  name: okapi-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: okapi
        image: okapi
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /mnt/config/config.yaml
          name: okapi-config
          subPath: config.yaml
      imagePullSecrets:
        - name: regcred
      volumes:
      - name: okapi-config
        configMap:
          name: okapi-configmap
