apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- clusterrole.yaml
- configmap.yaml
- rolebinding.yaml
- serviceaccount.yaml
- daemonset.yaml

namespace: default

commonLabels:
  app: promtail
