apiVersion: apps/v1
kind: Deployment
metadata:
  name: poker-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: poker
        image: poker
        args:
          - "-db=postgres://postgres:z5EdbhS0CFSFPvn788nVaopLCiJj1JedFb3UFhfHUY0=@10.43.19.40/postgres?sslmode=disable"
          # - "-db=postgres://postgres:postgres@postgres-service/poker?sslmode=disable"
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: regcred
