apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

commonLabels:
  app: poker

images:
- name: poker
  newName: docker.io/tomarrell/personal
  newTag: poker-e517f8d
