apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

commonLabels:
  app: poker

images:
- name: poker
  newName: docker.io/tomarrell/personal
  newTag: poker-e9fc1a4c7b63e9fe0aae9960a26ad2008578e47e
