# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pvc.yaml
- deployment.yaml
- service.yaml

namespace: default

commonLabels: 
  app: postgres
  
configMapGenerator:
- name: postgres-configmap
  env: postgres.env
