apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: city
        image: city
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: regcred
