apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

commonLabels:
  app: city

images:
- name: city
  newName: docker.io/tomarrell/personal
  newTag: city-3abf9f4
