apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

commonLabels:
  app: helloworld

images:
- name: helloworld
  newName: docker.io/tomarrell/personal
  newTag: helloworld
