apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

commonLabels:
  app: snake

images:
- name: snake
  newName: docker.io/tomarrell/personal
  newTag: snake-4cd6b39
